# Generated by Django 4.1.2 on 2022-10-19 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_shippingaddress_address2_shippingaddress_state'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='address',
            new_name='city',
        ),
    ]
