# Generated by Django 4.1.2 on 2022-10-20 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_rename_address_shippingaddress_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='email',
        ),
        migrations.AddField(
            model_name='customer',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
